// src/app/code-object/ui-runtime/components/video-player.tsx
import { useEffect, useState } from 'react'

export type VideoPlayerModel = {
  autoplay: boolean
  controls: boolean
  fit: 'contain' | 'cover'
  loop: boolean
  muted: boolean
  poster?: string
  src: string
  title: string
}

export type VideoPlayerProps = Partial<Omit<VideoPlayerModel, 'src'>> &
  Pick<VideoPlayerModel, 'src'> & {
    className?: string
  }

function stringValue(value: unknown): string {
  return typeof value === 'string' ? value.trim() : ''
}

export function normalizeVideoPlayerModel(value: Record<string, unknown>): VideoPlayerModel {
  return {
    autoplay: value.autoplay === true,
    controls: value.controls !== false,
    fit: value.fit === 'cover' ? 'cover' : 'contain',
    loop: value.loop === true,
    muted: value.muted === true,
    ...(stringValue(value.poster) ? { poster: stringValue(value.poster) } : {}),
    src: stringValue(value.src),
    title: stringValue(value.title) || 'Video player'
  }
}

export function VideoPlayer({
  autoplay = false,
  className = '',
  controls = true,
  fit = 'contain',
  loop = false,
  muted = false,
  poster,
  src,
  title = 'Video player'
}: VideoPlayerProps) {
  const [loading, setLoading] = useState(Boolean(src))
  const [failed, setFailed] = useState(false)

  useEffect(() => {
    setLoading(Boolean(src))
    setFailed(false)
  }, [src])

  return (
    <div
      className={`relative isolate size-full min-h-0 min-w-0 overflow-hidden bg-black text-white ${className}`}
      data-video-player=""
    >
      {src ? (
        <video
          aria-label={title}
          autoPlay={autoplay}
          className={`block size-full ${fit === 'cover' ? 'object-cover' : 'object-contain'}`}
          controls={controls}
          loop={loop}
          muted={muted}
          onError={() => {
            setLoading(false)
            setFailed(true)
          }}
          onLoadedData={() => {
            setLoading(false)
            setFailed(false)
          }}
          playsInline
          poster={poster}
          preload="metadata"
          src={src}
        />
      ) : null}
      {loading && !failed ? (
        <div className="pointer-events-none absolute inset-0 grid place-items-center bg-black/35 text-xs text-white/70">
          Loading video…
        </div>
      ) : null}
      {failed || !src ? (
        <div className="absolute inset-0 grid place-items-center bg-black px-6 text-center text-xs text-white/65">
          {failed ? 'This video could not be loaded.' : 'No video source is available.'}
        </div>
      ) : null}
    </div>
  )
}

// src/components/ui/VideoPlayer.vue
<script setup lang="ts">
import { computed, ref, useTemplateRef, watch } from 'vue'

const {
  autoplay = false,
  controls = true,
  errorMessage,
  fit = 'contain',
  loop = false,
  muted = false,
  poster,
  preload = 'metadata',
  src,
  label = 'Video player'
} = defineProps<{
  autoplay?: boolean
  controls?: boolean
  errorMessage?: string
  fit?: 'contain' | 'cover'
  loop?: boolean
  muted?: boolean
  poster?: string
  preload?: 'auto' | 'metadata' | 'none'
  src: string
  label?: string
}>()

const emit = defineEmits<{
  error: []
  loaded: []
  pause: []
  play: []
}>()

const video = useTemplateRef<HTMLVideoElement>('video')
const loading = ref(Boolean(src))
const playbackError = ref('')
const resolvedError = computed(() => errorMessage || playbackError.value)

watch(
  () => src,
  (value) => {
    loading.value = Boolean(value)
    playbackError.value = ''
  }
)

function handleLoaded() {
  loading.value = false
  playbackError.value = ''
  emit('loaded')
}

function handleError() {
  loading.value = false
  playbackError.value = 'This video could not be loaded.'
  emit('error')
}

function mediaElement(): HTMLVideoElement | null {
  return video.value
}

defineExpose({ mediaElement })
</script>

<template>
  <div
    class="relative isolate size-full min-h-0 min-w-0 overflow-hidden bg-black text-white"
    data-test-id="video-player"
  >
    <video
      v-if="src"
      ref="video"
      :aria-label="label"
      :autoplay="autoplay"
      class="block size-full"
      :class="fit === 'cover' ? 'object-cover' : 'object-contain'"
      :controls="controls"
      :loop="loop"
      :muted="muted"
      :playsinline="true"
      :poster="poster"
      :preload="preload"
      :src="src"
      @error="handleError"
      @loadeddata="handleLoaded"
      @pause="emit('pause')"
      @play="emit('play')"
    />
    <div
      v-if="loading && !resolvedError"
      class="pointer-events-none absolute inset-0 grid place-items-center bg-black/30"
      role="status"
    >
      <span class="flex items-center gap-2 text-[11px] text-white/75">
        <icon-lucide-loader-circle class="size-4 animate-spin" />
        Loading video…
      </span>
    </div>
    <div
      v-if="resolvedError || !src"
      class="absolute inset-0 grid place-items-center bg-black px-5 text-center"
      role="alert"
    >
      <span class="flex max-w-xs flex-col items-center gap-2 text-[11px] text-white/65">
        <icon-lucide-video-off class="size-5" />
        {{ resolvedError || 'No video source is available.' }}
      </span>
    </div>
  </div>
</template>
